config/routes.rb
Rails.application.routes.draw do

  resources :invoices do 
    collection do
      post :redraw
      post :auto_complete
    end
    member do
      put :attach
      post :discard
    end
  end

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  # mass assignment
  attr_accessible :user_id, :account_id, :access
  attr_accessible :uniqid, :status, :invoice_date, :payment_due_date, :order_number, :order_date, :tax, :note

  # invoice has a creator
  # invoice belongs to a count
  # invoice may have no opporunities or more than one opportunities.
  # invoice have its tasks, which is different task to opportuntiy, so delete invoice will delete the invoice task.
  belongs_to   :user
  belongs_to   :account
  has_many    :invoice_opportunities, :dependent => :destroy
  has_many    :opportunities, :through => :invoice_opportunities, :uniq => true, :order => "opportunity_id DESC"
  has_many    :tasks, :as => :asset, :dependent => :destroy
  
  # validations
  validates_presence_of :user_id, :account_id
  validates_presence_of :uniqid, :status, :invoice_date, :payment_due_date
  validates :uniqid, :presence=>true, :uniqueness=>true

  # scopes
  year=Time.now.strftime("%Y")
  scope :thisyear, lambda { {:conditions => ["created_at > '01/01/#{year}'"] }}
  scope :my, lambda { accessible_by(User.current_ability) }
  scope :text_search, lambda { |query|
    # postgresql does not like to compare string to integer field
    if query =~ /^\d+$/
      query = query.gsub(/[^\w\s\-\.'\p{L}]/u, '').strip
      where('upper(:uniqid) LIKE upper(:uniqid) OR opportunities.id = :id', :name => "%#{query}%", :id => query)
    else
      search('uniqid_cont' => query).result
    end
  }

  # extensions
  has_ransackable_associations %w(account opportunities activities comments tasks)
  ransack_can_autocomplete
  acts_as_commentable
  has_paper_trail :ignore => [ :subscribed_users ]
  sortable :by => ['invoice_date DESC'], :default => 'created_at DESC'


  # save invoice with account info.
  #------------------------------------
  def save_with_account(params)
    params[:account].delete(:id) if params[:account][:id].blank?
    account = Account.create_or_select_for(self, params[:account])
    # may be account_invoice relation
    self.account = account
    # if in opportunity landing page.
    self.opportunities << Opportunity.find(params[:opportunity])  unless params[:opportunity].blank?
    self.save
  end

  # make a unique_id of invoice
  #-------------------------------------
  def self.make_unique_id
    no = Setting.invoice_sequence_number
    no = Invoice.count if no.nil?
    changed = false
    while where(:uniqid =>"#{Setting.invoice_stem}_#{no}").exists? do
      no += 1
      changed = true
    end
    Setting.invoice_sequence_number = no if changed
    "#{Setting.invoice_stem}_#{no}"
  end


  #-------------------------------------
  def self.per_page; 20; end
  def emails; []; end
  def email_ids; []; end
  def subscribed_users; []; end
  def full_name; uniqid; end
  def name; uniqid; end


  #-----------------------------------
  def attach!(attachment)
    unless self.send("#{attachment.class.name.downcase}_ids").include?(attachment.id)
      self.send(attachment.class.name.tableize) << attachment
    end
  end

  #---------------------------------------
  def discard!(attachment)
    if attachment.is_a?(Task)
      attachment.update_attribute(:asset, nil)
    else # 
      self.send(attachment.class.name.tableize).delete(attachment)
    end
  end

  ActiveSupport.run_load_hooks(:fat_free_crm_invoice, self)
end

app/models/invoice_opportunity.rb
class InvoiceOpportunity < ActiveRecord::Base
  belongs_to :invoice
  belongs_to :opportunity
  # attr_accessible :title, :body
  validates_presence_of :invoice_id, :opportunity_id
  
  ActiveSupport.run_load_hooks(:fat_free_crm_invoice_opportunity, self)
end

app/controllers/invoices_controller.rb
class InvoicesController < EntitiesController

  before_filter :load_settings
  before_filter :set_params, :only => [:index,:redraw]


  # GET /invoices
  # GET /invoices.xls
  # GET /invoices.csv
  # GET /invoices.rss
  # GET /invoices.atom
  #-------------------------------------------
  def index
    @invoices = get_invoices(:page => params[:page], :per_page =>params[:per_page])

    respond_with @invoices do |format|
      format.xls { render :layout => 'header' }
      format.csv { render :csv => @invoices }
    end
  end

  # GET /invoices/1
  # AJAX  /invoices/1
  #-----------------------------------------
  def show
    @invoice = Invoice.find(params[:id])
    @timeline = timeline(@invoice)
    respond_with(@invoice)
  end

  # GET /invoices/new
  # AJAX /invoices/new
  #-----------------------------------------
  def new
    # invoice, account
    @invoice.attributes = {:user=>current_user}
    @account     = Account.new(:user => current_user, :access => Setting.default_access)
    @accounts    = Account.my.order('name')
    @invoice.user_id = current_user.id
    @invoice.uniqid = next_unique_id
    @invoice.user_id = current_user.id


    # related object
    if params[:related]
      model, id = params[:related].split('_')
      if related = model.classify.constantize.my.find_by_id(id)
        instance_variable_set("@#{model}", related)
        @account = related.account if related.respond_to?(:account) && !related.account.nil?
      else
        respond_to_related_not_found(model) and return
      end
    end

    respond_with(@invoice)
  end

  # GET /invoices/1/edit
  #---------------------------------------------
  def edit
    # prepare current infor to edit
    @account = @invoice.account

    # for account _select
    @accounts    = Account.my.order('name')

    # retrieve previous model if any, so that we render previous info (close its form)
    if params[:previous].to_s =~ /(\d+)\z/
      @previous = Invoice.my.find_by_id($1) || $1.to_i
    end

    respond_with(@invoice)
  end

  # POST /invoices
  #----------------------------------------------------------
  def create
    # create invoice
    @invoice = Invoice.new(params[:invoice])
    @invoice.user_id = current_user.id if @invoice.user_id.blank?

    # create account if neccessaory, and assoc with invoice
    if @invoice.save_with_account(params)
      set_options
      @invoices = get_invoices
    else  # fail to save
      @accounts = Account.my.order('name')
      unless params[:account][:id].blank?
        @account = Account.find(params[:account][:id])
      else
          if request.referer =~ /\/accounts\/(.+)$/
            @account = Account.find($1) # related account
          else
            @account = Account.new(:user => current_user)
          end
      end
    end

  end

  # PUT /invoices/1
  #-------------------------------------------------------
  def update
    @invoice.update_attributes(params[:invoice])
    @invoice.save_with_account(params)
  end

  # DELETE /invoices/1
  #-------------------------------------------------------
  def destroy
    @invoice.destroy
    set_options
    @invoices = get_invoices(:page => params[:page], :per_page =>params[:per_page])
    respond_with(@invoices) do |format|
      format.html { respond_to_destroy(:html) }
      format.js   { respond_to_destroy(:ajax) }
    end
  end

  # POST|AJAX /invoices/redraw
  #-------------------------------------------------------
  def redraw
    @invoices = get_invoices(:page =>1, :per_page => params[:per_page])
    set_options
    respond_with(@invoices) do |format|
      format.js { render :index }
    end
  end

  # POST|AJAX /invoices/auto_complete
  #----------------------------------------------------------
  # move to  invoice_hooks.rb
 

  def next_unique_id
     Invoice.make_unique_id
  end

  def load_settings
    @status = Setting.unroll(:invoice_status)
    @tax_options = Setting[:invoice_tax_options]
  end

  private
  alias :get_invoices   :get_list_of_records

  def respond_to_destroy(method)
    if method == :ajax
      if called_from_index_page?
        get_data_for_sidebar
        @invoices = get_invoices
        if @invoices.blank?
          @invoices = get_invoices(:page => current_page - 1) if current_page > 1
          render :index and return
        end
      else # Called from related asset.
        self.current_page = 1
      end
      # At this point render destroy.js
    else
      self.current_page = 1
      flash[:notice] = t(:msg_asset_deleted, @invoice.name)
      redirect_to invoices_path
    end
  end
    

  def get_data_for_sidebar(related = false)
  end


  def set_params
    current_user.pref[:invoices_per_page] = params[:per_page] if params[:per_page]
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
  def section *args
    super
  end
end

app/views/invoices/_edit.html.haml
.remote
  = simple_form_for(@invoice, :html => one_submit_only, :remote => true) do |f|
    = link_to_close edit_invoice_path(@invoice)
    = f.hidden_field :user_id
    -#= hidden_field_tag "contact",  "#{@contact.id  if @contact}"

    = f.error_messages :object_name => t('invoice')

    = render "invoices/top_section", :f => f
    -# render "fields/edit_custom_field_group", :f => f
    -# render "shared/add_comment",        :f => f
    -# render "fields/groups",             :f => f
    -# render "entities/permissions",      :f => f, :entity => @invoice

    .buttonbar
      = f.submit t(:save_invoice), :onclick => %/$("account_assigned_to").value = $F("invoice_assigned_to"); if ($("account_id").visible()) { $("account_id").enable(); }/
      #{t :or}
      = link_to_cancel edit_invoice_path(@invoice)

app/views/invoices/_form.html.haml
= form_for @invoice do |f|
  - if @invoice.errors.any?
    #error_explanation
      %h2= "#{pluralize(@invoice.errors.count, "error")} prohibited this invoice from being saved:"
      %ul
        - @invoice.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :status
    = f.text_field :status
  .field
    = f.label :invoice_date
    = f.date_select :invoice_date
  .field
    = f.label :order_date
    = f.date_select :order_date
  .field
    = f.label :tax
    = f.text_field :tax
  .field
    = f.label :payment_due_date
    = f.date_select :payment_due_date
  .field
    = f.label :note
    = f.text_area :note
  .actions
    = f.submit 'Save'

app/views/invoices/_index_brief.html.haml
%li.highlight[invoice]
  - if invoice.status
    .strip{:class=>invoice.status}= t(invoice.status)
  - else
    .strip.white #{t :other}

  %ul.tools
    - if can?(:update, invoice)
      %li= link_to_edit(invoice)
      
    - if shown_on_landing_page? && controller_name != 'accounts'
      %li= link_to_discard(invoice)

    - if can?(:destroy, invoice)
      %li= link_to_delete(invoice)
      
  .indent
    - if (account = invoice.account) && account.id
      == #{t :from} #{link_to_if can?(:read, account), account.name, account_path(account)}
    =link_to_if can?(:read, :invoice), "#{invoice.uniqid} #{invoice.invoice_date}", invoice
      
    %tt
      &ndash;
      - user_name = invoice.user_id == current_user.id ? t(:me) : invoice.user.try(:full_name)
      - if user_name
        = t(:added_by, :time_ago => time_ago_in_words(invoice.created_at), :user => user_name)
      - else
        = t(:added_ago, :value => time_ago_in_words(invoice.created_at))

    = hook(:invoice, self, :invoice => invoice)      

app/views/invoices/_inline_styles.html.haml
-# invoice status color styles
- Setting.invoice_status_color.each do |key, value|
  li.invoice .#{key} { background:#{value}; }

app/views/invoices/_invoice.html.haml
- if (params['controller'] == 'invoices') and (template = template_for_current_view).present?
  = render(template, :invoice => invoice)
- else
  -# default view
  = render 'invoices/index_brief', :invoice => invoice

app/views/invoices/_new.html.haml
= simple_form_for(@invoice, :html => one_submit_only, :remote => true) do |f|
  = link_to_close new_invoice_path
  = f.hidden_field :user_id
  = hidden_field_tag "opportunity",  "#{@opportunity.id  if @opportunity}"

  = f.error_messages :object_name => t('invoice')

  = render "invoices/top_section", :f => f
  -# render "fields/edit_custom_field_group", :f => f
  -# render "shared/add_comment",        :f => f
  -# render "fields/groups",             :f => f
  -# render "entities/permissions",      :f => f, :entity => @invoice

  .buttonbar
    = f.submit t(:create_invoice), :onclick => %/$("account_assigned_to").value = $F("invoice_assigned_to"); if ($("account_id").visible()) { $("account_id").enable(); }/
    #{t :or}
    = link_to_cancel new_invoice_path

app/views/invoices/_title_bar.html.haml
#confirm{ hidden }
.title_tools#menu
  = link_to_inline(:edit_invoice, edit_invoice_path(@invoice), :text => t(:edit)) + " | "
  = link_to_function(t(:delete) + '?', confirm_delete(@invoice))
.title_tools#buttons
  = view_buttons
.title#edit_invoice_title
  = h(@invoice.full_name)
  = image_tag("loading.gif", :size => :thumb, :id => "loading", :style => "display: none;")

%div#edit_invoice{ hidden }

app/views/invoices/_top_section.html.haml
= hook(:invoice_top_section, self, :f => f) do
  .section
    %table
      %tr
        %td
          .label.req.top #{t :uniqid}:
          = f.text_field :uniqid, :style=>"width:325px"
        %td= spacer
        %td
          .label.req.top #{t :status}:
          = f.select :status, @status, { :selected => @invoice.status ? @invoice.status.to_sym : nil }, { :style=>"width:160px" }

    %table{ :border=>0, :width=>500, :cellpadding =>0, :cellspacing=>0 }
      %tr
        %td
          .label.req #{t :invoice_date}:
          = f.text_field :invoice_date, :value => f.object.invoice_date, :style => "width:110px;", :autocomplete => :off, :class => 'date'
        %td= spacer
        %td
          .label.req #{t :payment_due_date}:
          = f.text_field :payment_due_date, :value => f.object.payment_due_date, :style => "width:110px;", :autocomplete => :off, :class => 'date'
        %td= spacer
        %td
          .label #{t :order_number}:
          = f.text_field :order_number, :value => f.object.order_number, :style => "width:110px;", :autocomplete => :off
        %td= spacer
        %td
          .label #{t :order_date}:
          = f.text_field :order_date, :value => f.object.order_date, :style => "width:110px;", :autocomplete => :off, :class => 'date'
    = fields_for(@account) do |a|
      = a.hidden_field :user_id
      = a.hidden_field :access
      = a.hidden_field :assigned_to
      %table
        %tr
          %td
            != account_select_or_create(a) do |options|
              -# Add [-- None --] account choice when editing existing opportunity that has an account.
              - options[:selected] = @invoice.id || 0
              - options[:include_blank] = true #t(:select_none) unless @invoice.new_record? || @invoice.account.blank?
          %td
            .label #{t :tax}:
            = f.select :tax, @tax_options, { :selected => @invoice.tax }, { :style=>"width:160px" }
                
    %table
      %tr
        %td
          .label #{t :note}:
          =f.text_area :note, :value => f.object.note, :style=>"width:500px;"

app/views/invoices/create.js.haml
- entity_name = controller.controller_name.singularize.underscore
- @entity = instance_variable_get("@#{entity_name}")
- create_id = "create_#{entity_name}"

- if @entity.valid?
  jQuery('##{create_id}_arrow').html(crm.COLLAPSED);
  jQuery('##{create_id}_title').html('#{ j t(entity_name.pluralize) }');
  jQuery('##{create_id}').slideUp(250);
  jQuery('##{entity_name.pluralize}').prepend('#{ j render(:partial => entity_name, :collection => [ @entity ]) }');
  jQuery('##{dom_id(@entity)}').effect("highlight", { duration:1500 });

  - if called_from_index_page?
    -#= refresh_sidebar(:index, :filters)
    jQuery('#paginate').html('#{ j render(:partial => "shared/paginate_with_per_page") }');
  - elsif called_from_landing_page?("accounts") # Opportunity created on Account landing page: refresh Account summary.
    - @invoice.reload
    -#= refresh_sidebar_for(:accounts, :show, :summary)
  - else # Opportunity created on Contact landing page: refresh recent items list.
    jQuery('#recently').html('#{ j render(:partial => "shared/recently") }');
  crm.flick('empty', 'remove');

- else
  jQuery('##{create_id}').html('#{ j render(:partial => "new") }');
  crm.create_or_select_account(#{ request.referer =~ /\/accounts\// || @account.id.blank? });
  jQuery('##{create_id}').effect("shake", { duration:250, distance: 6 });
  jQuery('#new_#{entity_name} input[type!=hidden]').first().focus();

app/views/invoices/edit.js.haml
- entity_name = controller.controller_name.singularize.underscore #account
- @entity = instance_variable_get("@#{entity_name}")
- id = dom_id(@entity)

- if params[:cancel].true? # <--------------------- Hide [Edit]

  - if called_from_landing_page?
    crm.flip_form('edit_#{entity_name}');
    crm.set_title('edit_#{entity_name}', '#{h @entity.name}');
  - else                                            # Called from index page...
    jQuery('##{id}').replaceWith('#{ j render(:partial => entity_name, :collection => [ @entity ]) }');

- else # <----------------------------------------- Show requested [Edit Opportunity] form.

  - if params[:cancel].blank?                       # Called from opportunities list item...
    - if @previous                                  # Hide open [Edit Opportunity] form if any.
      - if @previous.is_a?(Invoice)
        jQuery('##{dom_id(@previous)}').replaceWith('#{ j render(:partial => entity_name, :collection => [ @previous ]) }');
      - else
        crm.flick('#{entity_name}_#{@previous}', 'remove');

    -# Disable onMouseOver for the list item.
    crm.highlight_off('#{id}');
    -# Hide [Create] form if any.
    crm.hide_form('create_#{entity_name}');
    -# Show [Edit] form.
    jQuery('##{id}').html('#{ j render(:partial => "edit") }');

  - elsif params[:cancel].false?                    # Called from title of the opportunity landing page...
    jQuery('#edit_#{entity_name}').html('#{ j render(:partial => "edit") }');
    crm.flip_form('edit_#{entity_name}');
    crm.set_title('edit_#{entity_name}', "#{t :edit} #{h @invoice.name}");

  crm.create_or_select_account(#{ request.referer =~ /\/accounts\// || @account.id.blank? });
  jQuery('#new_#{entity_name} input[type!=hidden]').first().focus();

app/views/invoices/index.html.haml
= styles_for :invocie

= render 'entities/title_bar'

.remote#create_invoice{ hidden }

-# render "search"

.remote#options{ hidden }

.list#invoices
  - if @invoices.any?
    = render @invoices
  - else
    = render "shared/empty"

#paginate= render "shared/paginate_with_per_page"
#export= render "shared/export"

= hook(:invoice_index_after, self)

app/views/invoices/index.js.haml
- entities = controller.controller_name # accounts
- @entities = instance_variable_get("@#{entities}")

- if @entities.any?
  jQuery('##{entities}').html('#{ j render(@entities) }');
- else
  jQuery('##{entities}').html('#{ j render(:partial => "shared/empty") }');

jQuery('#paginate').html('#{ j render(:partial => "shared/paginate_with_per_page") }');
jQuery('#export').html('#{ j render(:partial => "shared/export") }');
jQuery('#search_results_count').html('#{ j render(:text => t('search_results_count', :count => @search_results_count)) }');

app/views/invoices/show.html.haml
- if (template = template_for_current_view)
  = render(template, :invoice => @invoice)
- else

  -# default view

  = styles_for :task, :opportunity
  
  = render 'invoices/title_bar', :invoice => @invoice

  = render "comments/new", :commentable => @invoice
  = render :partial => "shared/timeline", :collection => @timeline

  = hook(:show_invoice_bottom, self) do

    = render :partial => "tasks/tasks", :locals => {:object => @invoice}

    = render :partial => "opportunities/opportunities", :locals => {:object => @invoice}
    
    = render :partial => "versions/versions", :locals => {:object => @invoice}

    = load_select_popups_for(@invoice, :tasks, :opportunities)

app/views/invoices/update.js.haml
- entity_name = controller.controller_name.singularize.underscore #account
- @entity = instance_variable_get("@#{entity_name}")
- id = called_from_landing_page? ? "edit_#{entity_name}" : dom_id(@entity)

- if @entity.errors.empty?
  - if called_from_landing_page?
    crm.flip_form('edit_#{entity_name}');
    crm.set_title('edit_#{entity_name}', '#{h @entity.name}');
    -#= refresh_sidebar(:show, :summary)
  - else
    jQuery('##{id}').replaceWith('#{ j render(:partial => entity_name, :collection => [ @entity ]) }');
    jQuery('##{id}').effect("highlight", { duration:1500 });
    - if called_from_index_page?
      -#= refresh_sidebar(:index, :filters)
    - elsif called_from_landing_page?(:accounts)
      -#= refresh_sidebar_for(:accounts, :show, :summary)
    - else
      jQuery('#recently').replaceWith('#{ j render(:partial => "shared/recently") }');
- else
  jQuery('##{id}').html('#{ j render(:partial => "edit") }');
  crm.create_or_select_account(#{ request.referer =~ /\/accounts\// || @account.id.blank? });
  jQuery('##{id}').effect("shake", { duration:250, distance: 6 });
  jQuery('##{dom_id(@entity, :edit)} input[type!=hidden]').first().focus();